# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-yaml
    -   id: debug-statements
    -   id: requirements-txt-fixer
-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    -   id: black
        exclude: corpora/wikipedia/WikiExtractor.py
-   repo: https://github.com/PyCQA/pydocstyle
    rev: '5.0.2'
    hooks:
    -   id: pydocstyle
        exclude: corpora/wikipedia/WikiExtractor.py
-   repo: https://gitlab.com/PyCQA/flake8
    rev: '3.7.9'
    hooks:
    -   id: flake8
        exclude: corpora/wikipedia/WikiExtractor.py
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.2
    hooks:
    -   id: isort
        exclude: corpora/wikipedia/WikiExtractor.py
